version: '3.4'

services:
  repos.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  repos.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
